
sudo: false

language: node_js

node_js:
  - "stable"

cache:
  directories:
    - "node_modules"

services:
  - docker

before_install:
  - docker-compose up --build 
  
install:
  - npm ci
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
   - docker ps -a
script:
    - npm run start &
    - sleep 10; npm run ci:test
