
sudo: false

language: node_js

node_js:
  - "stable"

cache:
  directories:
    - "node_modules"

services:
  - docker

before_install:
  - docker-compose up --build -d

before_script:
  # - psql -c 'create database travis_ci_test;' -U postgres
  - docker ps -a
script:
    - npm run ci:test
