
sudo: false

language: node_js

node_js:
  - "stable"

cache:
  directories:
    - "node_modules"

services:
  - docker

before_install:
  - docker-compose up --build -d
  - docker ps -a

script:
    # - npm run ci:test
    - docker-compose run app npm run test
