# docker-compose.override.yml
version: "3.3"
services:
  app:
    container_name: dockerapp
    env_file: .env
    volumes:
      - .:/home/node/
      - /home/node/node_modules
      - server_db:/var/lib/postgresql/data
volumes:
  server_db:
