# docker-compose.yml
version: "3.3"
services:

  postgres:
    image: postgres:11.2-alpine
     
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks: 
      - webnet
    ports:
      - "4201:5432"
  app:
    build: .
    command: npm run dev
    ports:
      - "3000:${PORT}"
      - "9229:9229"
    environment:
      DB_HOST: postgres
    networks: 
      - webnet
networks: 
  webnet:
  
