# docker-compose.override.yml
version: "3.3"
services:
  app:
    env_file: .env
    volumes:
      - .:/home/app/
      - /home/app/node_modules
      - server_db:/var/lib/postgresql/data
volumes:
  server_db:
